In [36]:
from pandas import Series
se=Series([1,2,3,4,6])
se

0    1
1    2
2    3
3    4
4    6
dtype: int64

In [37]:
import pandas as pd
a=[1,2,3,4]
myvar=pd.Series(a)
myvar


0    1
1    2
2    3
3    4
dtype: int64

In [38]:
se2=Series([100,200,300],index=['a','b','c'])
se2

a    100
b    200
c    300
dtype: int64

In [39]:
se2=Series([100,200,300],index=['a','b','c'])
se2['c']


300

In [40]:
salary={'john':1000,'tim':2000,'rahul':3000}
se=Series(salary)
se


john     1000
tim      2000
rahul    3000
dtype: int64

In [42]:
salary={'john':1000,'tim':2000,'rahul':3000}
se=Series(salary)
se
salary
se['tim']


2000

In [43]:
import numpy
x=numpy.array([15,80,10,25])
x

array([15, 80, 10, 25])

In [44]:
import numpy
x=numpy.array([15,80,10,25])
print(x)


[15 80 10 25]


In [45]:
import numpy as np
y=np.array([40,10,20,50])
print(y)


[40 10 20 50]


In [46]:
import numpy as np
z=np.array((40,20,10,60))
print(z)


[40 20 10 60]


In [47]:
import numpy as np
x1=np.array([[10,50,20],[60,70,30]])
print(x1)


[[10 50 20]
 [60 70 30]]


In [48]:
import numpy as np
y1=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(y1)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


In [49]:
import numpy as np
y1=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(y1.ndim)


2


In [50]:
import numpy as np
w=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,5]]])
print(w)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 4 5]]]


In [51]:
import numpy as np
w=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,5]]])
print(w[1,1,0])


1


In [52]:
import numpy as np
w=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,5]]])
print(w[0,1,2])


6


In [53]:
import numpy as np
w=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,5]]])
print(w.ndim)



3
